# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’

target 'iOS-Kick-On' do
  # Pods for iOS-Kick-On
  pod 'CYLTabBarController'
  pod 'AFNetworking’
  pod 'IQKeyboardManager’
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod ‘YYModel’
  pod 'SWTableViewCell'
  pod 'Masonry'
  pod 'ReactiveObjC'
  
  
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # if you use swift, comment this rac version
  #pod 'ReactiveCocoa', '5.0.0-alpha.3'

  

  target 'iOS-Kick-OnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
