# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'iOS-Kick-On' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS-Kick-On
  pod 'AFNetworking’
  pod 'IQKeyboardManager’
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod ‘YYModel’
  pod 'SWTableViewCell'
  pod 'Masonry'
  
  target 'iOS-Kick-OnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
